const TYPE = {
  REGISTER: 'REGISTER',
  ACTIVATE_ACCOUNT: 'ACTIVATE_ACCOUNT',
  LOGIN: 'LOGIN',
  LOG_OUT: 'LOG_OUT',
  ADD_POT: 'ADD_POT',
  VIEW_A_POT: 'VIEW_A_POT',
  VIEW_ALL_POTS: 'VIEW_POT',
  GET_ALL_POTS: 'GET_ALL_POTS',
  VIEW_POTS_IN_NEED: 'POTS_IN_NEED',
  VIEW_MY_POTS: 'VIEW_MY_POTS',
  ADD_DONATION: 'ADD_DONATION',
  EDIT_POT: 'EDIT_POT',
};

export default TYPE;
