const TYPE = {
  REGISTER: 'REGISTER',
  ACTIVATE_ACCOUNT: 'ACTIVATE_ACCOUNT',
  LOGIN: 'LOGIN',
  ADD_POT: 'ADD_POT',
  VIEW_ALL_POTS: 'VIEW_POT',
  ADD_DONATION: 'ADD_DONATION',
};

export default TYPE;
