const TYPE = {
  REGISTER: 'REGISTER',
  ACTIVATE_ACCOUNT: 'ACTIVATE_ACCOUNT',
  LOGIN: 'LOGIN',
  LOG_OUT: 'LOG_OUT',
  ADD_POT: 'ADD_POT',
  VIEW_ALL_POTS: 'VIEW_ALL_POT',
  VIEW_A_POT: 'VIEW_A_POT',
  ADD_DONATION: 'ADD_DONATION',
};

export default TYPE;
